services:
  seed:
    build: medusa-starter-default
    command: yarn seed
    restart: "no"
    ports:
      - 9001:9001
    environment:
      REDIS_URL: redis://redis:6379/0
      CACHE_REDIS_URL: redis://redis:6379/1
      EVENTS_REDIS_URL: redis://redis:6379/2
      WE_REDIS_URL: redis://redis:6379/3
      DATABASE_URL: postgres://medusa-starter:medusa-password@postgres/medusa-starter?ssl_mode=disable
      POSTGRES_URL: postgres://medusa-starter:medusa-password@postgres/medusa-starter?ssl_mode=disable